### ISSUE TITLE
Daemon Error: Unicode Decode Error on OpenELEC 6.0.1

### ISSUE THREAD

**Issue by sabi1999** [scakemyer/plugin.video.quasar#210]
While starting Quasar I'm prompted with a Daemon error:

UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 1: ordinal not in range(128)

Here is my logfile: http://pastebin.com/ki28inGS

Thanks for your amazing work!

**Comment by lightglitch** [comment]
I'm also having this issue on my android version.

**Comment by carl181** [comment]
+1 the addin works well until a restart and I have the same error : Unicode on OpenELEC 6.0.1 (Quasar 0.9.22). Thank you for your work 

tion in thread Thread-2:
        Traceback (most recent call last):
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 551, in __b
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/threading.py", line 504, in run
          File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 141, in quasard_thread
            proc = start_quasard(stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
          File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 101, in start_quasard
            quasar_dir, quasar_binary = get_quasar_binary()
          File "/storage/.kodi/addons/plugin.video.quasar/resources/site-packages/quasar/daemon.py", line 91, in get_quasar_binary
            shutil.rmtree(path)
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 245, in rmtree
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/shutil.py", line 239, in rmtree
          File "/home/stephan/projects/openelec-6.0/build.OpenELEC-imx6.arm-6.0.1/Python-2.7.3/.install_pkg/usr/lib/python2.7/posixpath.py", line 71, in join
        UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)
gMessage - Write: sent command error !

**Comment by sabi1999** [comment]
I fixed my issue by uninstalling Quasar. Deleting the /userdata/database/addons19.db and then reinstalling Quasar again.

**Comment by lightglitch** [comment]
That solution didn't worked for me.

**Comment by Sjodda** [comment]
It did not work for me neither. Do we need to start a new issue or can this be reopen?

**Comment by scakemyer** [comment]
I've had my share of debugging encoding issues, and don't have an available device to test so I can't try fixes for this one. I'd appreciate if you guys could find how to fix this on OpenELEC and send a PR.

**Comment by lightglitch** [comment]
@scakemyer I'm using it on a nvidia shield tv but I will try to debug the issue.

**Comment by wilmeta** [comment]
Same problem here. Openelec 6.0 32bits build. I used the addon a couple days since the daemon error, and after that, impossible to use, even reinstalling the addon. The only thing that works for me is resetting the whole KODI system, but that's a litlle bit time-consuming every couple days. :(

**Comment by m4xc4v413r4** [comment]
@sabi1999 Can you try updating Openelec to the latest version, I can't replicate this on my x86-64 Openelec installation.

**Comment by sabi1999** [comment]
I already fixed my issue a month ago by uninstalling Quasar. Deleting the /userdata/database/addons19.db and then reinstalling Quasar again. My Openelec version is always the latest.

**Comment by m4xc4v413r4** [comment]
wtf, I didn't realize this was a month old, why the hell did I receive this on my feed yesterday...

**Comment by scakemyer** [comment]
Because you just commented on it and there was a reply afterwards? ;) Unless more users report this is still an issue in OpenELEC 6.0.3, maybe the 32bit version only, this seems to be solved.

**Comment by scakemyer** [comment]
Because you just commented on it and there was a reply afterwards? ;) Unless more users report this is still an issue in OpenELEC 6.0.3 (~~maybe the 32bit version only~~ 32-bit builds are deprecated with OpenELEC 6.0) this seems to be solved.

**Comment by m4xc4v413r4** [comment]
When I commented 5 days ago the last comment was already 16 days before that (which I didn't realise) and I got it on my feed as if it was new. Anyway, doesn't seem to be a problem here so carry on :)

**Comment by Sjodda** [comment]
Why this bustle to close issues on no fact from any users with problem??

Im running a ION machine with 64-bit version Openelec 6.0.3 and the issue is still there i cant use Quasar...

**Comment by m4xc4v413r4** [comment]
@Sjodda why do people keep thinking anyone is going to fix their problems when they don't even bother to link a log of that said problem.

**Comment by Sjodda** [comment]
I did open my issue with a log... But that was closed instantly.... 

https://github.com/scakemyer/plugin.video.quasar/issues/240

**Comment by scakemyer** [comment]
It was closed instantly as a duplicate because you didn't bother to check for a similar issue, I later re-opened this issue right here at your request, and a closed issue doesn't mean someone else won't find a solution to your problem. If so I'll be happy to merge a fix.

**Comment by jaimepd** [comment]
The same problem in Android ARM. 

UnicodeDecodeError: 'ascii' codec can't decode byte...

¿Should I create a new issue?

**Comment by lightglitch** [comment]
I was able to solve my issue by changing daemon.py at line 67 to:
```python
            shutil.rmtree(dest_binary_dir.encode("ascii"))
```

**Comment by popra** [comment]
Have the same issue on Android TV

**Comment by parruc** [comment]
lightglitch solution works for me but I had to do it also on line 88 of the same file. Hope this helps

**Comment by jaimepd** [comment]
It's worked for me.

Thank you!

**Comment by fuhgeddaboudit** [comment]
parruc, thank you for your addition after I changed line 67 and 88 everything is working great again.
