### ISSUE TITLE
Posibile memory leaks

### ISSUE THREAD

**Issue by johnnyslt** [scakemyer/plugin.video.quasar#441]
I think quasar binary might have some memory leaks, because after some time quasar ram usage is way to high.

I have a RPi 1 with 512Mb, with OpenElec 8.0 build from source, but this happens also on official OpenElec 6.0.x

Yesterday, after 7 hours runtime:

![quasar_7hours](https://cloud.githubusercontent.com/assets/1221249/14064734/0dad01ce-f417-11e5-8441-0b87293f0908.PNG)
 
Yesterday, after reboot:

![quasar_fresh_start](https://cloud.githubusercontent.com/assets/1221249/14064736/254c689c-f417-11e5-913c-c9c7b083677f.PNG)

Today, 14 hours after above reboot:

![quasar_14_hours](https://cloud.githubusercontent.com/assets/1221249/14064739/34f077f2-f417-11e5-9b5c-addad5c2df77.PNG)

Log from that 14 hours runtime : http://sprunge.us/ULfQ

**Comment by scakemyer** [comment]
Mostly fixed in scakemyer/quasar@e17706c, probably even more leaks fixed in libtorrent. Seeing very stable memory usage between 25MB and 30MB over time, around 45-50MB while streaming and going back down right after, even with background handling and some seeding (a little higher in that case which is normal).

**Comment by sagarun** [comment]
This is still an issue.
`[302400.959533] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[302400.959551] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[302400.959574] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[302400.959597] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[302400.959620] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[302400.959643] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[302448.706652] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[302448.706681] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[302448.706697] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[302448.706717] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[304259.906570] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[304259.906599] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[304259.906616] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[304259.906637] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[304560.965013] INFO:w
[304560.965034]       Not tainted 4.4.27-9-osmc #1
[304560.965044] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[304560.965054] kworker/u8:1    D 80760204     0 21073      2 0x00000000
[304560.965091] Workqueue: kmmcd mmc_rescan
[304560.965130] [<80760204>] (__schedule) from [<80760894>] (schedule+0x5c/0xcc)
[304560.965154] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[304560.965178] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[304560.965198] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[304560.965217] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[304560.965239] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[304560.965261] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[304560.965283] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[304560.965305] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[306073.451867] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[306073.451886] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[306073.451894] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[306073.451906] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[306600.970160] INFO: task kworker/u8:1:21073 blocked for more than 120 seconds.
[306600.970181]       Not tainted 4.4.27-9-osmc #1
[306600.970190] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[306600.970201] kworker/u8:1    D 80760204     0 21073      2 0x00000000
[306600.970239] Workqueue: kmmcd mmc_rescan
[306600.970277] [<80760204>] (__schedule) from [<80760894>] (schedule+0x5c/0xcc)
[306600.970302] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[306600.970325] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[306600.970346] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[306600.970365] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[306600.970388] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[306600.970411] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[306600.970433] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[306600.970456] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[307882.352024] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[307882.352041] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[307882.352049] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[307882.352060] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[308760.975526] INFO: task kworker/u8:0:21176 blocked for more than 120 seconds.
[308760.975541]       Not tainted 4.4.27-9-osmc #1
[308760.975545] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[308760.975561] kworker/u8:0    D 80760204     0 21176      2 0x00000000
[308760.975583] Workqueue: kmmcd mmc_rescan
[308760.975606] [<80760204>] (__schedule) from [<80760894>] (schedule+0x5c/0xcc)
[308760.975622] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[308760.975634] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[308760.975646] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[308760.975655] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[308760.975667] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[308760.975678] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[308760.975689] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[308760.975700] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[309693.796644] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[309693.796673] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[309693.796706] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[309693.796727] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[310440.979929] INFO: task kworker/u8:2:21193 blocked for more than 120 seconds.
[310440.979953]       Not tainted 4.4.27-9-osmc #1
[310440.979964] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[310440.979974] kworker/u8:2    D 80760204     0 21193      2 0x00000000
[310440.980011] Workqueue: kmmcd mmc_rescan
[310440.980049] [<80760204>] (__schedule) from [<80760894>] (schedule+0x5c/0xcc)
[310440.980075] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[310440.980099] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[310440.980120] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[310440.980138] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[310440.980161] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[310440.980183] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[310440.980204] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[310440.980226] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[310560.980213] INFO: task kworker/u8:2:21193 blocked for more than 120 seconds.
[310560.980237]       Not tainted 4.4.27-9-osmc #1
[310560.980246] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[310560.980257] kworker/u8:2    D 80760204     0 21193      2 0x00000000
[310560.980296] Workqueue: kmmcd mmc_rescan
[310560.980334] [<80760204>] (__schedule) from [<80760894>] (schedule+0x5c/0xcc)
[310560.980358] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[310560.980382] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[310560.980403] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[310560.980422] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[310560.980445] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[310560.980468] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[310560.980489] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[310560.980512] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[311507.358121] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[311507.358147] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[311507.358164] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[311507.358183] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[311880.970609] INFO: task kworker/u8:0:21176 blocked for more than 120 seconds.
[311880.970632]       Not tainted 4.4.27-9-osmc #1
[311880.970641] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[311880.970653] kworker/u8:0    D 80760204     0 21176      2 0x00000000
[311880.970689] Workqueue: kmmcd mmc_rescan    [<80760894>] (schedule+0x5c/0xcc)
[311880.970753] [<80760894>] (schedule) from [<805c6ffc>] (__mmc_claim_host.constprop.11+0xdc/0x198)
[311880.970777] [<805c6ffc>] (__mmc_claim_host.constprop.11) from [<805c70e4>] (mmc_get_card+0x2c/0x30)
[311880.970801] [<805c70e4>] (mmc_get_card) from [<805d14c8>] (mmc_sd_detect+0x2c/0x94)
[311880.970819] [<805d14c8>] (mmc_sd_detect) from [<805caa50>] (mmc_rescan+0xcc/0x4b8)
[311880.970841] [<805caa50>] (mmc_rescan) from [<800501e4>] (process_one_work+0x15c/0x5c4)
[311880.970862] [<800501e4>] (process_one_work) from [<800506a0>] (worker_thread+0x54/0x5a0)
[311880.970882] [<800506a0>] (worker_thread) from [<80058804>] (kthread+0x180/0x198)
[311880.970906] [<80058804>] (kthread) from [<80016fc8>] (ret_from_fork+0x14/0x2c)
[313322.428285] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[313322.428314] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[313322.428330] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[313322.428351] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[315134.904592] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[315134.904610] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[315134.904619] sd 2:0:0:0: [sdb] tag#0 ASC=0x0 ASCQ=0x0
[315134.904630] sd 2:0:0:0: [sdb] tag#0 CDB: opcode=0xa1 a1 06 20 00 00 00 00 00 00 e5 00 00
[316941.282489] sd 2:0:0:0: [sdb] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x07 driverbyte=0x08
[316941.282507] sd 2:0:0:0: [sdb] tag#0 Sense Key : 0x4 [current] [descriptor]
[327921.829488] Exception stack(0xad8ebfb0 to 0xad8ebff8)
[327921.829495] bfa0:                                     01938da8 00000003 000e7390 00026081
[327921.829503] bfc0: fffffffd 01938da8 018cd8e0 00000000 76f26f10 000eb100 000eb0c8 018cd8e0
[327921.829511] bfe0: 000eaae8 7e8415a0 0008993f 00026080 80010030 ffffffff
[327921.829517] Mem-Info:
[327921.829531] active_anon:168534 inactive_anon:1227 isolated_anon:0
 active_file:1594 inactive_file:1594 isolated_file:0
 unevictable:0 dirty:0 writeback:0 unstable:0
 slab_reclaimable:2284 slab_unreclaimable:3593
 mapped:1635 shmem:1338 pagetables:735 bounce:0
 free:3059 free_pcp:413 free_cma:146
[327921.829561] Normal free:12236kB min:12288kB low:15360kB high:18432kB active_anon:674136kB inactive_anon:4908kB active_file:6376kB inactive_file:6376kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:770048kB managed:751028kB mlocked:0kB dirty:0kB writeback:0kB mapped:6540kB shmem:5352kB slab_reclaimable:9136kB slab_unreclaimable:14372kB kernel_stack:2160kB pagetables:2940kB unstable:0kB bounce:0kB free_pcp:1652kB local_pcp:140kB free_cma:584kB writeback_tmp:0kB pages_scanned:79876 all_unreclaimable? yes
[327921.829566] lowmem_reserve[]: 0 0
[327921.829576] Normal: 211*4kB (UE) 146*8kB (UE) 113*16kB (UE) 39*32kB (UE) 40*64kB (UE) 22*128kB (UE) 7*256kB (UC) 0*512kB 0*1024kB 0*2048kB 0*4096kB = 12236kB
[327921.829615] 4562 total pagecache pages
[327921.829623] 0 pages in swap cache
[327921.829628] Swap cache stats: add 0, delete 0, find 0/0
[327921.829632] Free swap  = 0kB
[327921.829635] Total swap = 0kB
[327921.829639] 192512 pages RAM
[327921.829643] 0 pages HighMem/MovableOnly
[327921.829648] 4755 pages reserved
[327921.829651] 2048 pages cma reserved
[327921.829656] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds swapents oom_score_adj name
[327921.829685] [  180]     0   180     2104      466       7       0        0             0 systemd-journal
[327921.829695] [  199]     0   199     2665      133       7       0        0         -1000 systemd-udevd
[327921.829708] [  584]     0   584      793       61       6       0        0             0 systemd-logind
[327921.829717] [  586]   105   586      838       69       6       0        0             0 avahi-daemon
[327921.829725] [  587]   104   587     1228      128       6       0        0          -900 dbus-daemon
[327921.829733] [  588]     0   588      825       46       5       0        0             0 irqbalance
[327921.829742] [  596]     0   596     1660      129       8       0        0             0 connmand
[327921.829751] [  597]   105   597      810       55       5       0        0             0 avahi-daemon
[327921.829760] [  599]     0   599      473       44       6       0        0             0 eventlircd
[327921.829768] [  612]   110   612      956       60       6       0        0             0 dnsmasq
[327921.829776] [  619]  1000   619     1377      112       6       0        0             0 udisks-glue
[327921.829786] [  621]     0   621     6534      208      11       0        0             0 udisks-daemon
[327921.829794] [  622]     0   622     1737       80       7       0        0             0 udisks-daemon
[327921.829802] [  623]     0   623     1181      140       5       0        0             0 openvpn
[327921.829812] [  624]     0   624     1654      115       6       0        0         -1000 sshd
[327921.829820] [  626]   109   626     9979      244      13       0        0             0 transmission-da
[327921.829829] [  630]     0   630      718       62       6       0        0             0 mediacenter
[327921.829838] [  635]     0   635     8739      197      12       0        0             0 polkitd
[327921.829846] [  673]     0   673     1375      107       7       0        0             0 sudo
[327921.829855] [  678]  1000   678   185523    43048     207       0        0             0 kodi.bin
[327921.829863] [  684]     0   684      937       83       7       0        0             0 rpcbind
[327921.829872] [  734]     0   734     1082      153       5       0        0             0 rpc.mountd
[327921.829880] [  748]     0   748     1357       75       7       0        0             0 wpa_supplicant
[327921.829891] [  792]     0   792      597      100       5       0        0             0 mount.ntfs
[327921.829901] [  798]     0   798      383       21       6       0        0             0 hciattach
[327921.829908] [  803]     0   803      958       37       6       0        0             0 bluetoothd
[327921.829918] [ 1123]   106  1123     1237      108       7       0        0             0 ntpd
[327921.829927] [13097]  1000 13097     1054      107       5       0        0             0 systemd
[327921.829935] [13099]  1000 13099     5824      329       8       0        0             0 (sd-pam)
[327921.829943] [13149]  1000 13149     1383      334       9       0        0             0 tmux
[327921.829950] [13154]  1000 13154     1365      313       7       0        0             0 bash
[327921.829959] [13244]  1000 13244   359231   120582     280       0        0             0 quasar
[327921.829968] [21493]     0 21493     2693      186       9       0        0             0 sshd
[327921.829976] [21497]  1000 21497     2693      184       9       0        0             0 sshd
[327921.829984] [21498]  1000 21498     1414      348       8       0        0             0 bash
[327921.829993] [21517]  1000 21517     2318      467       8       0        0             0 python2
[327921.829999] Out of memory: Kill process 13244 (quasar) score 643 or sacrifice child
[327921.830070] Killed process 13244 (quasar) total-vm:1436924kB, anon-rss:482328kB, file-rss:0kB`
