### ISSUE TITLE
Quasar crashes many times since 0.9.61

### ISSUE THREAD

**Issue by krde** [scakemyer/plugin.video.quasar#691]
Hi friend, Quasar keeps crashing in a loop since 0.9.61 to 0.9.63 when Kodi 16.1 is started (win8 & Android arm) until Quasar gives up... but... with the 0.9.60 version works perfect (win8 & Android arm).
Here you get the two logs...
first... the 0.9.60 working perfect...
http://pastebin.com/dczxuaSq

and then... the 0.9.63 crashing...
http://pastebin.com/5HgBJR8k

**Comment by scakemyer** [comment]
Already fixed in scakemyer/quasar@ad840da, but that is not your main problem here, see #673 and a more detailed explanation in #679.

**Comment by krde** [comment]
Thanks @scakemyer ... but... the settings are already on TVDB (as default) anyway i tried changing to Trakt and even changing to TMDB and still having the same problem...
![quasar](https://cloud.githubusercontent.com/assets/25309042/22521729/e3c385f6-e8b0-11e6-88d4-a61812601f2f.jpg)

**Comment by scakemyer** [comment]
I added new JSON-RPC checks in the last version to prevent other crashes related to that, and they're telling me you might not have remote control options enabled and/or your Windows firewall blocking Quasar:
```
ERRO  xbmc         ▶ VideoLibraryGetMovies  No available JSON-RPC connection to Kodi
ERRO  xbmc         ▶ VideoLibraryGetShows  No available JSON-RPC connection to Kodi
```

**Comment by krde** [comment]
Hmmm... both? there is no firewall in the android device and i get same problem... anyway... i don't think that there is any firewall problem... due to is working perfectly with 0.9.60... about the remote control options... i've never touched them before and it was always working well... anyway i tried enabling some remote control options in Kodi just to try... and.. still same problem.

**Comment by scakemyer** [comment]
Let's try with the logs from your Android box then, because that's all I can conclude from those logs on Windows :(

**Comment by thatguy93** [comment]
Im having the same problem on my minix U1, browsing genres takes forever and i get like 10 errors which say "bad status getting movie (numbers)" i tried doing a fresh install but still the same, ill post logs later

**Comment by krde** [comment]
I will try to send the log from the android system as soon as i can
