### ISSUE TITLE
New episodes are not being marked as watched

### ISSUE THREAD

**Issue by KillerJoeBR** [scakemyer/plugin.video.quasar#833]
Hi there, it's me again.

So i did some testing with the new release and it does work for not-so-new episodes. They get marked as watched just fine. But it's not working for recent ones. 

It doesn't show the bad status message like before, but after playback it's not being marked as watched. And i'm pretty sure it worked fine before the 0.9.76 release. (i would need to install it again to be sure, but i'm 90% sure it was working for recent episodes just fine)

My Quasar scraper is TVDB wich is also my library scraper. TVDB is the oficial default kodi scraper for series, right? So it should work with this one i think. 

Later i can get a log, but i think it would look just like the ones before. But just ask for one and i will provide.

Thanks

**Comment by elgatito** [comment]
When you start playing something with Quasar it knows only TMDB id, so to find correct Kodi library item Quasar needs to do this actions:
Use already-known TMDB id -> Find TVDB id -> Find library item based on TVDB id (because Kodi saves only TVDB id in the database, when TVDB is selected as scraper).

The bad thing, as I've said before, TMDB does not always have definition of TVDB id.
That is why Quasar not always getting library item from Kodi.

The best/fastest/most reliable way is to use TMDB scraper for Quasar-created shows. Or wait till solution is found.

**Comment by KillerJoeBR** [comment]
Ok i get that the episode info is getting lost somewhere. But why it did work before?

Here is the log from Quasar 0.9.75:  http://paste.ubuntu.com/24374008/

Tried 3 series episodes and they all got marked as watched at the end. The first episode didn't get marked as watched the first time, but i think that's because my library got updated while it was searching and the focus/selection went to the first episode during this and it got mixed up. Tried again and it worked.

**Comment by elgatito** [comment]
Since TMDB usually have TVDB id for Show itself, then Quasar can do on tmdb api ```https://api.themoviedb.org/3/tv/{tmdbid}/external_ids``` to get TVDB id, then with tvdb do ``` /series/{tvdbid}/episodes```
And use resulting episodes' ids to find correct Kodi library.

**Comment by KillerJoeBR** [comment]
Ok here is the log from Quasar 0.9.78: http://paste.ubuntu.com/24374134/

During playback i could see that all episodes didn't have titles in the description. In Quasar 0.9.75 they all had their correct titles in the description.

So that's probably the cause of the problem. So it worked in Quasar 0.9.75 and it's not working now in the new version. (since 0.9.76 i guess)

**Comment by KillerJoeBR** [comment]
Tried and old episode in Quasar 0.9.78 and it also doesn't show the episode title in the description. Just something like 8x13 etc. 

But it did get marked as watched. So even if it's not getting the title of the episode it still worked.  So I guess getting the title right is not everything. But it sure helps cause Quasar 0.9.75 gets that and even recent episodes are marked as watched.

**Comment by scakemyer** [comment]
@elgatito stop thinking of this in terms of having only TMDB or TVDB IDs or not, that assumption is what's screwing everything up here and if I f*cking knew you were seeing things that way I would have never merged all those PRs since 0.9.76. Keep. Things. Simple. We were using Kodi's library IDs to set things as watched, now even after spending hours reviewing your changes, I'm not sure anymore, and will have to spend a lot more time figuring out all this f*cking mess.

**Comment by KillerJoeBR** [comment]
Ok thanks for both of you trying to solve this. I appreciate all your efforts. Mistakes can happen, no big deal. We are all trying to make Quasar even better. 

Thanks

**Comment by scakemyer** [comment]
Actually solved in 0.9.78?

**Comment by KillerJoeBR** [comment]
No it's not solved. It is not working for any recent episode (like from last 2 months or so) and it is probably related to a change since 0.9.76 where episodes are not being identified correctly. With previous version the episode title was identified in the description during playback. But now we only get something like 7x18 episode in the description.

**Comment by KillerJoeBR** [comment]
Here is again log from Quasar 0.9.78 http://paste.ubuntu.com/24380265/  

--not marked as watched

Screenshot from description http://imgur.com/a/n4qjE

Log from Quasar 0.9.75 http://paste.ubuntu.com/24380283/

--marked as watched

Screenshot from description http://imgur.com/a/WCX3E

the change that is probably causing this is the way Quasar identifies the episode which changed from quasar 0.9.75 to quasar 0.9.76 when you guys tried a way to quasar to mark as watched episodes from the widget panel in kodi homescreen that didn't have id labels like when inside the library.

**Comment by ShlomiD83** [comment]
just noticed that its marking as watched when playing an episode from the homescreen widget..

**Comment by scakemyer** [comment]
There are both improvements and regressions since v0.9.76...

**Comment by KillerJoeBR** [comment]
ok i just tried with TMDB scraper to see if it would work this way and it also didn't mark as watched just like before.

To do this Test,I installed the TMDB scraper for TV Series then I changed the scraper in the Quasar settings, added a new series to my library using also TMDB as the scraper and it didn't work. So i guess TMDB scraper doesn't solve the issue.
